### ISSUE TITLE
question about test 

### ISSUE THREAD

**Issue by ebraham47** [binli123/dsmil-wsi#2]
Hi,
Thank you for making public this implementation of your very nice paper.
 would you please share python code for test or detect new WSI? i see just train scripts.
thanks

**Comment by binli123** [comment]
Are you asking about the complete testing workflow involving the patch extraction, attention computing, and patches to the stitched attention map? The patch extraction, attention computing are already included in the training scripts where part of the training dataset is hold-out for validation. However, they are not stitched but rather just attention scores for each patch which can be printed out as one of the model's returns. Standalone testing scripts for processing any given raw WSI and stitching patches back to WSI will be released soon. We are stilling figuring out an elegant way to put this purely in Python script since originally we relied on the Java-based [ImageJ](https://imagej.net/Fiji) to stitch the gigapixel images.

**Comment by binli123** [comment]
The scripts for cropping and testing WSIs at a single magnification are uploaded.
