### ISSUE TITLE
Generate features for another dataset

### ISSUE THREAD

**Issue by ritamartinspereira** [binli123/dsmil-wsi#91]
Hello, I was wondering if you could describe how you generated the pre-computed features provided in this repository so that i can  reproduce the same thing using a different dataset.
Thank you

**Comment by binli123** [comment]
Hello, I believe you can find instructions in the readme https://github.com/binli123/dsmil-wsi?tab=readme-ov-file#processing-raw-wsi-data

**Comment by ericwang10** [comment]
Hi,

Sorry for reopening this thread, but I had a few questions about training my own dataset.

Step 2: Crop patches
once we crop our WSI files into patches, do we need to manually separate them into training and testing datasets? 

Step 3: Train an embedder
Is the embedder only trained on the training dataset? Would we need to train another embedder for the test dataset or do we just use the original trained embedder?

If the tissue/classification problem is different, should I train my own embedder, or could I still use the one you provided? For example, using the Camelyon16 embedder from breast cancer lymph node tissue to identify epilepsy in brain tissue (different tissue and classification problem) 

Lastly, for cross-validation, would we have to train a separate embedder for each cross-validation fold since the training dataset is different?

Sorry if these questions are basic, I am new to these MIL techniques.

Thank you for your time!
